name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      new_version_string:
        description: 'New version string (eg, 0.4.4, 0.4.4-rc1)'
        required: true
        type: string

jobs:
  prepare_version:
    runs-on: ubuntu-latest
    outputs:
      new_version_tag: v${{ github.event.inputs.new_version_string }}
      new_version_number: ${{ github.event.inputs.new_version_string }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install tools
        run: cargo install cargo-workspaces

      - name: update crate versions& inter-dependency and block tag (handled later)
        env:
          TARGET_VERSION: ${{ github.event.inputs.new_version_string }}
        run: |
          echo "set workspace versions to $TARGET_VERSION"
          cargo ws version custom "$TARGET_VERSION" --all --exact --yes --no-git-commit

      - name: verify Cargo.lock is updated
        run: |
          cargo check --workspace --all-targets
          echo "cargo.lock is up-to-date"

      - name: Commit/Tag/Push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actor
          message: 'chore(release): prepare release v${{ github.event.inputs.new_version_string }}'
          tag: 'v${{ github.event.inputs.new_version_string }}'
          add: 'Cargo.toml av1an/Cargo.toml av1an-core/Cargo.toml Cargo.lock'
          push: true